export const SAMPLE_JOBS = [
  {
    id: 1,
    title: "Business Development Manager (BDM)",
    company: "Phonepe",
    location: "Bhopal, Indore, Raipur",
    regionName: "Central India",
    openings: 32,
    editDate: "13 Mar 2025",
    editedBy: "shashi@hunarr.ai",
  },
  {
    id: 2,
    title: "Software Developer",
    company: "Infosys",
    location: "Hyderabad",
    regionName: "South India",
    openings: 25,
    editDate: "12 Mar 2025",
    editedBy: "shashi@hunarr.ai",
  },
  {
    id: 3,
    title: "Customer Service Executive",
    company: "Croma",
    location: "Bangalore",
    regionName: "South India",
    openings: 29,
    editDate: "11 Mar 2025",
    editedBy: "shashi@hunarr.ai",
  },
  {
    id: 4,
    title: "Marketing Specialist",
    company: "Amazon",
    location: "Delhi",
    regionName: "North India",
    openings: 15,
    editDate: "10 Mar 2025",
    editedBy: "shashi@hunarr.ai",
  },
  {
    id: 5,
    title: "UI/UX Designer",
    company: "Wipro",
    location: "Mumbai",
    regionName: "West India",
    openings: 8,
    editDate: "09 Mar 2025",
    editedBy: "shashi@hunarr.ai",
  },
  {
    id: 6,
    title: "Data Analyst",
    company: "TCS",
    location: "Pune",
    regionName: "West India",
    openings: 12,
    editDate: "08 Mar 2025",
    editedBy: "shashi@hunarr.ai",
  },
];
